version: '3'

services:
  server:
    image: jbulicek/shopping-backend
    expose:
      - "3001"
    ports:
      - "3001:3001"
  client:
    image: jbulicek/shopping-frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - "server"