version: "3"
services:
  haystack-agent:
    image: expediadotcom/haystack-agent
    environment:
      JAVA_XMS: 128m
      haystack_env_agents_spans_port: 34000

  frontend:
    image: expediadotcom/opentracing-spring-haystack-example
    environment:
      APP_MODE: frontend
      SPRING_PROFILE: remote
      HAYSTACK_AGENT_HOST: haystack-agent
      BACKEND_URL: http://backend:9091
    ports:
      - "9090:9090"

  backend:
    image: expediadotcom/opentracing-spring-haystack-example
    environment:
      APP_MODE: backend
      SPRING_PROFILE: remote
      HAYSTACK_AGENT_HOST: haystack-agent
