version: "3"
services:
  storage-backend:
    image: expediadotcom/haystack-trace-backend-cassandra
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
    depends_on:
      - "cassandra"
      
  trace-reader:
    image: expediadotcom/haystack-trace-reader
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_BACKEND_CLIENT_HOST: "storage-backend"

  trace-indexer:
    image: expediadotcom/haystack-trace-indexer
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_BACKEND_CLIENT_HOST: "storage-backend"
    depends_on:
      - "elasticsearch"

  ui:
    environment:
      HAYSTACK_OVERRIDES_CONFIG_PATH: /data/connectors.json
      HAYSTACK_CONNECTORS_TRACES_CONNECTOR__NAME: "haystack"
      HAYSTACK_CONNECTORS_TRENDS_CONNECTOR__NAME: "stub"
