version: "3"
services:
  metrictank:
    image: grafana/metrictank:0.10.1
    environment:
      MT_HTTP_MULTI_TENANT: "false"
      MT_CARBON_IN_ENABLED: "false"
      MT_KAFKA_MDM_IN_ENABLED: "true"
      MT_CASSANDRA_ADDRS: "cassandra:9042"
      MT_KAFKA_MDM_IN_BROKERS: "kafkasvc:9092"
      MT_CASSANDRA_IDX_HOSTS: "cassandra:9042"
      MT_STATS_ENABLED: "false"
      MT_MEMORY_IDX_TAG_SUPPORT: "true"
    depends_on:
      - "kafkasvc"
    restart: on-failure
#    ports:
#      - "6060:6060"

  trends-transformer:
    image: expediadotcom/haystack-span-timeseries-transformer
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_HEALTH_STATUS_PATH: "/app/isHealthy"
      HAYSTACK_PROP_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "kafkasvc:9092"
      JAVA_XMS: 128m
    depends_on:
      - "kafkasvc"
    restart: always

  trends-aggregator:
    image: expediadotcom/haystack-timeseries-aggregator
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_HEALTH_STATUS_PATH: "/app/isHealthy"
      HAYSTACK_PROP_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "kafkasvc:9092"
      JAVA_XMS: 128m
    depends_on:
      - "kafkasvc"
    restart: always

  ui:
    environment:
      HAYSTACK_OVERRIDES_CONFIG_PATH: /data/connectors.json
      HAYSTACK_CONNECTORS_TRENDS_CONNECTOR__NAME: "haystack"
      HAYSTACK_CONNECTORS_TRENDS_METRIC__TANK__URL: "http://metrictank:6060"
